version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextDB
      POSTGRES_USER: nextuser
      POSTGRES_PASSWORD: myN3XTpass
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: nextcloud:latest
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - configs:/var/www/html/config
      - data:/var/www/html/data
    networks:
      - frontend
      - backend
    ports:
      - 8080:80
    environment:
      POSTGRES_DB: nextDB
      POSTGRES_USER: nextuser
      POSTGRES_PASSWORD: myN3XTpass
      POSTGRES_HOST: next_db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: 10.65.100.7 devopstest devopstest.vallsnet.local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  nextcloud:
  apps:
  configs:
  data:
  db:
