version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud_db
      POSTGRES_USER: nextuser
      POSTGRES_PASSWORD: mysqlpassword
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: nextcloud:latest
    depends_on:
      - db
    volumes:
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-configs:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    networks:
      - frontend
      - backend
    ports:
      - 8080:80
    environment:
      POSTGRES_DB: nextcloud_db
      POSTGRES_USER: nextcloud_db_user
      POSTGRES_PASSWORD: mysqlpassword
      POSTGRES_HOST: db:3306
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  nextcloud-apps:
  nextcloud-configs:
  nextcloud-data:
  nextcloud-db:
